# Generated by Django 5.2.6 on 2025-09-19 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(choices=[('ITA', 'Italian')], default='ITA', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('role_abbreviation', models.CharField(max_length=5)),
                ('permission', models.IntegerField(choices=[(1, 'Om'), (2, 'Tl'), (3, 'Wfm'), (4, 'Qa'), (5, 'Tc'), (6, 'Agent')])),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(choices=[('R1', 'Resolutions 1'), ('R2', 'Resolutions 2'), ('DSS', 'Dedicated SuperHost Suport'), ('EXP', 'Experience')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_surname', models.CharField(max_length=150)),
                ('employee_market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_market', to='timecard.market')),
                ('employee_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_role', to='timecard.role')),
                ('employee_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_skill', to='timecard.skill')),
            ],
        ),
    ]
