# Generated by Django 5.2.6 on 2025-09-20 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punched_in', models.DateTimeField(auto_now_add=True)),
                ('employee_project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_project_id_punch_in', to='timecard.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PunchOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punched_out', models.DateTimeField(auto_now_add=True)),
                ('employee_project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_project_id_punch_out', to='timecard.employee')),
            ],
        ),
    ]
